# Generated by Django 5.0.3 on 2024-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
